package com.drools.rule;

import cn.javgo.drools.dto.fact.RuleExecutionObject; // 规则执行对象
import cn.javgo.drools.dto.fact.RuleExecutionResult; // 规则执行结果
import cn.javgo.drools.dto.fact.DynamicEntity; // 动态实体类
import java.util.*;
import java.lang.*;

global RuleExecutionResult _result; // 全局变量

rule "test-1"

    salience 1
    no-loop true

    when
        // 条件 1：user 对象的 name 属性值为 "张三"，且 age 属性值大于 18 小于 30
        $user : DynamicEntity(identify == "user", name == "张三", age > 18 && age < 30)
        // 条件 2：order 对象的 price 属性值大于 1000
        $order : DynamicEntity(identify == "order", price > 1000)
    then
        System.out.println("test-1 触发");
        _result.setResult("status", "success");
end