package com.drools.rule;

import cn.javgo.drools.dto.fact.RuleExecutionObject; // 规则执行对象
import cn.javgo.drools.dto.fact.RuleExecutionResult; // 规则执行结果
import cn.javgo.drools.dto.fact.DynamicEntity; // 动态实体类
import cn.javgo.drools.model.RuleAction; // 规则动作
import java.util.*;
import java.lang.*;

global RuleExecutionResult _result; // 全局变量

rule "test-1"

    salience 1
    no-loop true

    when
        // 条件 1：user 对象的 name 属性值为 "张三"，且 age 属性值大于 18 小于 30
        $user : DynamicEntity(identify == "user", realAttributes["name"] == "张三", realAttributes["age"] > 18, realAttributes["age"] < 30)
        // 条件 2：order 对象的 price 属性值大于 1000
        $order : DynamicEntity(identify == "order", realAttributes["price"] > 1000)
    then
        // 将规则的回调 URL 加入到规则执行结果中（也就是全局变量 _result）
        // 1.从 RuleAction 中获取回调 URL
        String callbackUrl = new RuleAction().getCallbackUrl();
        // 2.将回调 URL 加入到规则执行结果中
        _result.setResult("callbackUrl",callbackUrl);
        // 3.将触发的规则名称加入到规则执行结果中
        _result.setResult("ruleName","test-1");
        // 4.将规则判断结果加入到规则执行结果中
        _result.setResult("result",true);
end